// gauntlet:all — runs shots, diff, styles, a11y, layout, vocab, perf in
// order, against ONE build/server (so the seven scripts don't each pay
// their own build+start cost), and writes gauntlet/out/SUMMARY.md: one
// table, one row per instrument, columns = instrument / files produced /
// headline number. A non-coder reads this table and nothing else.
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { ROOT, OUT_DIR, SHOTS_DIR, ensureDir, withServer } from "./lib.mjs";

const STEPS = ["shots", "diff", "styles", "a11y", "layout", "vocab", "perf"];
const TWENTY_MINUTES_SECONDS = 20 * 60;

function readJson(name) {
  const file = path.join(OUT_DIR, name);
  if (!fs.existsSync(file)) return null;
  try {
    return JSON.parse(fs.readFileSync(file, "utf-8"));
  } catch {
    return null;
  }
}

function writeSummary(timings, totalSeconds) {
  const diff = readJson("diff.json");
  const styles = readJson("styles.json");
  const a11y = readJson("a11y.json");
  const layout = readJson("layout.json");
  const vocab = readJson("vocab.json");
  const perf = readJson("perf.json");

  const shotsCount = fs.existsSync(SHOTS_DIR) ? fs.readdirSync(SHOTS_DIR).length : 0;

  const worstDiff =
    diff && !diff.seeded
      ? diff.images
          .filter((i) => i.mismatchPercent !== null)
          .sort((a, b) => b.mismatchPercent - a.mismatchPercent)[0]
      : null;

  const totalUnlistedStyles = styles
    ? styles.surfaces.reduce((sum, s) => sum + s.unlisted.length, 0)
    : null;
  const totalA11yViolations = a11y
    ? a11y.runs.reduce((sum, r) => sum + r.violationCount, 0)
    : null;
  const totalContrastFailures = a11y ? a11y.contrastFailures.length : null;
  const totalOverflow = layout
    ? layout.findings.reduce((sum, f) => sum + f.horizontalOverflowCount, 0)
    : null;
  const totalOverlap = layout
    ? layout.findings.reduce((sum, f) => sum + f.overlapCount, 0)
    : null;

  const rows = [
    ["shots", "gauntlet/out/shots/*.png", `${shotsCount} PNGs`],
    [
      "diff",
      "gauntlet/out/diff.json, gauntlet/out/diffs/*.png",
      diff
        ? diff.seeded
          ? "baseline seeded (no prior baseline existed)"
          : `worst mismatch: ${worstDiff ? `${worstDiff.mismatchPercent}% (${worstDiff.name})` : "n/a"}`
        : "n/a",
    ],
    [
      "styles",
      "gauntlet/out/styles.json",
      `${totalUnlistedStyles ?? "n/a"} unlisted colour/font values`,
    ],
    [
      "a11y",
      "gauntlet/out/a11y.json",
      `${totalA11yViolations ?? "n/a"} axe violations, ${totalContrastFailures ?? "n/a"} contrast failures`,
    ],
    [
      "layout",
      "gauntlet/out/layout.json",
      `${totalOverflow ?? "n/a"} horizontal overflows, ${totalOverlap ?? "n/a"} text overlaps`,
    ],
    ["vocab", "gauntlet/out/vocab.json", `${vocab ? vocab.hitCount : "n/a"} banned-term hits`],
    [
      "perf",
      "gauntlet/out/lhci/*.json, gauntlet/out/perf.json",
      perf
        ? perf.runs.map((r) => `${r.id}: P${r.scores.performance}/A${r.scores.accessibility}`).join(", ")
        : "n/a",
    ],
  ];

  const timingRows = timings.map((t) => `| ${t.step} | ${t.seconds}s |`).join("\n");

  const md = `# Gauntlet Summary — cycle 0

Generated by \`npm run gauntlet:all\`. Total wall-clock: **${totalSeconds}s**.

A non-coder reads this table and nothing else — every JSON file listed
below has the full detail behind each headline number.

| Instrument | Files produced | Headline number |
|---|---|---|
${rows.map((r) => `| ${r[0]} | ${r[1]} | ${r[2]} |`).join("\n")}

## Timing per instrument

| Instrument | Seconds |
|---|---|
${timingRows}
| **Total** | **${totalSeconds}s** |
`;

  fs.writeFileSync(path.join(OUT_DIR, "SUMMARY.md"), md);
}

async function main() {
  ensureDir(OUT_DIR);
  const timings = [];
  const overallStart = Date.now();

  await withServer(async () => {
    for (const step of STEPS) {
      const stepStart = Date.now();
      console.log(`\n=== gauntlet:${step} ===`);
      execFileSync("node", [`gauntlet/scripts/${step}.mjs`], { cwd: ROOT, stdio: "inherit" });
      timings.push({ step, seconds: Number(((Date.now() - stepStart) / 1000).toFixed(1)) });
    }
  });

  const totalSeconds = Number(((Date.now() - overallStart) / 1000).toFixed(1));
  writeSummary(timings, totalSeconds);

  console.log(`\ngauntlet:all — done in ${totalSeconds}s. See gauntlet/out/SUMMARY.md.`);
  if (totalSeconds > TWENTY_MINUTES_SECONDS) {
    console.warn(
      `::warning::gauntlet:all took ${totalSeconds}s, over the 20-minute budget the ignition key set.`
    );
  }
}

main().catch((err) => {
  console.error("gauntlet:all failed:", err);
  process.exit(1);
});
